export const LOGOUT = "LOGOUT ";
export const LOGIN = "LOGIN";
export const GET_USERS = "GET_USERS";
export const GET_PAYMENTS = "GET_PAYMENTS";
export const ADD_PAYMENT = "ADD_PAYMENT";
export const SET_FILTERED_PAYMENTS_BY_USERS = "SET_FILTERED_PAYMENTS_BY_USERS";
export const SET_FILTERED_PAYMENTS_BY_TYPE = "SET_FILTERED_PAYMENTS_BY_TYPE";
export const SET_FILTERED_PAYMENTS_BY_STATUS =
  "SET_FILTERED_PAYMENTS_BY_STATUS";
export const SET_FILTERED_PAYMENTS_BY_RECEIVER =
  "SET_FILTERED_PAYMENTS_BY_RECEIVER";
export const SET_FILTERED_PAYMENTS_BY_AMOUNT =
  "SET_FILTERED_PAYMENTS_BY_AMOUNT";
export const SET_FILTERED_PAYMENTS_BY_DATE = "SET_FILTERED_PAYMENTS_BY_DATE";
export const SEARCH_USER_PAYMENTS = "SEARCH USER PAYMENTS";
